# Generated by Django 3.2.5 on 2022-07-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machineapp', '0002_alter_items_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
